"""
Runtime module for GraspGen-s600.

Provides BPU inference adapters and runtime utilities.
"""

from .calibration import (
    CalibrationTransform,
    EyeInHandValidation,
    ObservationPoseValidation,
    PointCorrespondenceCalibration,
    derive_robot_base_T_camera_from_hand_eye,
    eye_in_hand_metadata,
    load_gripper_T_camera,
    load_robot_base_T_camera,
    load_robot_base_T_camera_for_observation,
    load_robot_base_T_camera_for_planning,
    observation_pose_metadata,
    solve_robot_base_T_camera_from_points,
    transform_grasps,
    validate_observation_pose_from_health,
)
from .dofbot_servo import (
    ServoReading,
    angles_from_readings,
    deg_to_ticks,
    read_servo_angle_deg,
    read_servo_angles_deg,
    read_servo_ticks,
    servo_limits_deg,
    tick_resolution_deg,
    ticks_to_deg,
    write_servo_angle_deg,
)
from .grasp_filtering import CandidateSelection, select_grasp_candidate
from .hand_eye import (
    HandEyeCalibrationResult,
    HandEyeMotionPair,
    HandEyeSample,
    hand_eye_result_summary,
    solve_hand_eye,
    solve_hand_eye_from_motions,
)
from .hbm_graspgen_runtime import (
    InferenceResult,
    NormalizedPointCloud,
    S600GraspRuntime,
    get_nested,
    load_yaml_config,
    normalize_point_cloud,
    result_to_response,
    validate_point_cloud,
)
from .kinematics import ForwardKinematicsResult, forward_kinematics, forward_kinematics_with_metadata
from .perception import SegmentationResult, segment_object_point_cloud
from .point_cloud_icp import (
    ICPResult,
    icp_point_to_plane,
    icp_result_summary,
    register_pair,
    voxel_downsample,
)
from .pose_scout import TableViewScore, estimate_dominant_plane, score_rgb_image, score_table_view
from .table_markers import (
    ColoredPointCloud,
    DetectedTableMarker,
    TableMarkerDetection,
    TargetPoseCalibration,
    build_robot_points_for_detection,
    build_target_points_for_detection,
    detect_table_markers,
    detection_summary,
    load_colored_point_cloud_ply,
    load_configured_colored_point_cloud,
    solve_camera_T_target_from_detection,
    target_pose_summary,
)

__all__ = [
    "CalibrationTransform",
    "CandidateSelection",
    "ColoredPointCloud",
    "DetectedTableMarker",
    "EyeInHandValidation",
    "ForwardKinematicsResult",
    "HandEyeCalibrationResult",
    "HandEyeMotionPair",
    "HandEyeSample",
    "ICPResult",
    "InferenceResult",
    "NormalizedPointCloud",
    "ObservationPoseValidation",
    "PointCorrespondenceCalibration",
    "S600GraspRuntime",
    "SegmentationResult",
    "ServoReading",
    "TableMarkerDetection",
    "TargetPoseCalibration",
    "TableViewScore",
    "angles_from_readings",
    "build_robot_points_for_detection",
    "build_target_points_for_detection",
    "deg_to_ticks",
    "derive_robot_base_T_camera_from_hand_eye",
    "detect_table_markers",
    "detection_summary",
    "estimate_dominant_plane",
    "eye_in_hand_metadata",
    "forward_kinematics",
    "forward_kinematics_with_metadata",
    "get_nested",
    "hand_eye_result_summary",
    "icp_point_to_plane",
    "icp_result_summary",
    "load_gripper_T_camera",
    "load_robot_base_T_camera",
    "load_colored_point_cloud_ply",
    "load_configured_colored_point_cloud",
    "load_robot_base_T_camera_for_observation",
    "load_robot_base_T_camera_for_planning",
    "load_yaml_config",
    "normalize_point_cloud",
    "observation_pose_metadata",
    "read_servo_angle_deg",
    "read_servo_angles_deg",
    "read_servo_ticks",
    "result_to_response",
    "score_rgb_image",
    "score_table_view",
    "register_pair",
    "segment_object_point_cloud",
    "servo_limits_deg",
    "solve_camera_T_target_from_detection",
    "solve_hand_eye",
    "solve_hand_eye_from_motions",
    "solve_robot_base_T_camera_from_points",
    "select_grasp_candidate",
    "target_pose_summary",
    "tick_resolution_deg",
    "ticks_to_deg",
    "transform_grasps",
    "validate_observation_pose_from_health",
    "validate_point_cloud",
    "voxel_downsample",
    "write_servo_angle_deg",
]
